name: ImplodusTravel
main: me.ninjamandalorian.ImplodusTravel.ImplodusTravel
version: 1.0.0
api-version: 1.19
description: Interactive exploration plugin for travelling across the world.
author: NinjaMandalorian
depend: [Vault]
softdepend: [Towny]

commands:
  implodustravel:
    description: Primary command
    softdepend: [Vault]
    aliases:
      - itravel
  